#!/usr/bin/env bash
#Stops the 4-to_infinity_and_beyond_script
pid=$(pidof bash)
counter=0

for id in $pid
do
    counter=$((counter+1))
    if  [ $counter == 2 ]
    then
	i_d=$id
	break
    fi

done
kill "$i_d"
