#!/usr/bin/env bash

statements=('Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School')
for i in 0 1 2 3 4 5 6 7 8 9
do
	echo  ${statements[i]}
done
