#!/usr/bin/env bash
#Displays numbers from 1 to 100
NUMBER=1
while [[ $NUMBER -lt 101 ]]
do
    #check if number is a multiple of 3 and 5
    mod_3=$((NUMBER % 3))
    mod_5=$((NUMBER % 5))
    if [[ $mod_3 -eq 0 && $mod_5 -eq 0 ]]
    then
	echo "FizzBuzz"
    elif [[ $mod_3 -eq 0 ]]
    then
	echo "Fizz"
    elif [[ $mod_5 -eq 0 ]]
    then
	echo "Buzz"
    else
	echo $NUMBER
    fi

    ((NUMBER++))
done
