#!/usr/bin/env bash
#Displays 'Best School' 9 times, then displays, 'Hi!' and then display the final 'Best School' using a while loop and a nested for loop
counter=0
LIMIT=10

while [ "$counter"  -lt "$LIMIT" ]
do
	echo "Best School"
	if [ "$counter" == 8 ]
	then
		echo "Hi"
	fi
	counter=$((counter+1))
done
exit 0
