#!/usr/bin/env bash
#Displays 'bad luck from China'on the 4th iteration, 'bad luck from Japan' on the 9th iteration, 'bad luck from Italy; on the 17th.
counter=1
LIMIT=20

while [ "$counter" -le "$LIMIT" ]
do
	echo "$counter"
	case "$counter" in
	    4)
		echo "bad luck from China"
		;;
	    9)
		echo "bad luck from Japan"
		;;
	    17)
		echo "bad luck from Italy"
		;;
	    *)
		;;
	esac
	
	counter=$((counter + 1))
done
