#!/usr/bin/env bash
#Displays the contents of the current directory in a list format

FILES=$(ls ./*)
for file in $FILES
do
    length_of_file="${#file}"
    for((i=0; i<length_of_file; i++))
    do
	char="${file:i:1}"
	if [ "$char" == "-" ]
	then
	    index="$i"
	    start_index=$((index+2))
	    end_index=$length_of_file
	    final_string=$(cut -c "$start_index"-"$end_index"<<<"$file")
	    echo "$final_string"
	    break
	fi
    done
done


    
