#!/usr/bin/env bash
# changes the IP address for localhost and facebook.com

sed -i '/127.0.0.1/d' etc/hosts

echo "127.0.0.2       localhost" >> etc/hosts
echo "8.8.8.8       facebook.com" >> etc/hosts
